export default {
	UPDATE_SEEK_LOAN_MODAL: 'UPDATE_SEEK_LOAN_MODAL',
	UPDATE_SEEK_LOAN_MODAL_VISIBILITY: 'UPDATE_SEEK_LOAN_MODAL_VISIBILITY',
	UPDATE_SEEK_LOAN_MODAL_LOADED: 'UPDATE_SEEK_LOAN_MODAL_LOADED'
}