export default {
    UPDATE_SEEKING_FORM_FIRST_NAME: 'UPDATE_SEEKING_FORM_FIRST_NAME',
    UPDATE_SEEKING_FORM_LAST_NAME: 'UPDATE_SEEKING_FORM_LAST_NAME',
    UPDATE_SEEKING_FORM_EMAIL: 'UPDATE_SEEKING_FORM_EMAIL'
}