export default {
	UPDATE_SEEKING_LOAN_FORM: 'UPDATE_SEEKING_LOAN_FORM',
	SUBMIT_SEEKING_LOAN_FORM: 'SUBMIT_SEEKING_LOAN_FORM',
	VERIFY_SEEKING_LOAN_INPUT: 'VERIFY_SEEKING_LOAN_INPUT',
	RESET_ONE_SEEKING_LOAN_INPUT: 'RESET_ONE_SEEKING_LOAN_INPUT',
	CLEAR_SEEKING_LOAN_FORM: 'CLEAR_SEEKING_LOAN_FORM'
}