export default {
	SUBMIT_REGISTER_FORM: 'SUBMIT_REGISTER_FORM',
	UPDATE_REGISTERED_FORM: 'UPDATE_REGISTERED_FORM',
	//UPDATE_REGISTERED_FIRST_NAME: 'UPDATE_REGISTERED_FIRST_NAME',
	//UPDATE_REGISTERED_LAST_NAME: "UPDATE_REGISTERED_LAST_NAME",
	//UPDATE_REGISTERED_EMAIL: 'UPDATE_REGISTERED_EMAIL',
	//UPDATE_REGISTERED_PASSWORD: 'UPDATE_REGISTERED_PASSWORD',
	//UPDATE_REGISTERED_ERRORS: 'UPDATE_REGISTERED_ERRORS'
}