export default {
	UPDATE_EMAIL_INPUT: 'UPDATE_EMAIL_INPUT',
	UPDATE_PASSWORD_INPUT: 'UPDATE_PASSWORD_INPUT',
	UPDATE_LOGIN_ATTEMPTS: 'SUBMIT_LOGIN_CREDENTIALS',
	UPDATE_USER_AUTHENTICATION: 'UPDATE_USER_AUTHENTICATION',
	SUBMIT_LOGIN_CREDENTIALS: 'SUBMIT_LOGIN_CREDENTIALS',
	CLEAR_LOGIN_CREDENTIALS: 'CLEAR_LOGIN_CREDENTIALS',
	VALIDATE_LOGIN_CREDS: 'VALIDATE_LOGIN_CREDS',
	UPDATE_LOGIN_ERROR: 'UPDATE_LOGIN_ERROR'
}